export type SaoPauloZone="Zona Leste"|"Zona Norte"|"Zona Sul"|"Zona Oeste"|"Centro"|"Não classificada";

const groups:Record<Exclude<SaoPauloZone,"Não classificada">,string[]>={
  "Zona Leste":["AGUA RASA","ARICANDUVA","ARTUR ALVIM","BELEM","BELENZINHO","BRAS","CANGAIBA","CARRAO","CIDADE LIDER","CIDADE PATRIARCA","CIDADE TIRADENTES","ERMELINO MATARAZZO","GUAIANASES","IGUATEMI","ITAIM PAULISTA","ITAQUERA","JARDIM ANALIA FRANCO","JARDIM HELENA","JOSE BONIFACIO","LAJEADO","MOOCA","PARQUE DO CARMO","PARQUE SAO JORGE","PENHA","PONTE RASA","QUARTA PARADA","SAO LUCAS","SAO MATEUS","SAO MIGUEL","SAO RAFAEL","SAPOPEMBA","TATUAPE","VILA ALPINA","VILA CARMOSINA","VILA CARRAO","VILA CURUCA","VILA EMA","VILA FORMOSA","VILA GOMES CARDIM","VILA GUILHERMINA","VILA JACUI","VILA MATILDE","VILA PRUDENTE","VILA RE","VILA REGENTE FEIJO"],
  "Zona Norte":["ANHANGUERA","BRASILANDIA","CACHOEIRINHA","CASA VERDE","FREGUESIA DO O","JACANA","JARAGUA","JARDIM BRASIL","JARDIM JAPAO","JARDIM SAO PAULO","LAUZANE","LIMAO","MANDAQUI","PARADA INGLESA","PARQUE NOVO MUNDO","PERUS","PIRITUBA","SANTANA","TREMEMBE","TUCURUVI","VILA ALBERTINA","VILA GUILHERME","VILA GUSTAVO","VILA MARIA","VILA MAZZEI","VILA MEDEIROS","VILA NOVA CACHOEIRINHA","VILA NOVA MAZZEI","VILA PAULICEIA","VILA SABRINA","SAO DOMINGOS"],
  "Zona Sul":["AMERICANOPOLIS","BOSQUE DA SAUDE","BROOKLIN","CAMPO BELO","CAMPO GRANDE","CAMPO LIMPO","CAPAO REDONDO","CHACARA SANTO ANTONIO","CIDADE ADEMAR","CIDADE DUTRA","CIDADE MONCOES","CURSINO","GRAJAU","INDIANOPOLIS","INTERLAGOS","IPIRANGA","ITAIM BIBI","JABAQUARA","JARDIM AEROPORTO","JARDIM ANGELA","JARDIM MARAJOARA","JARDIM PRUDENCIA","JARDIM SAO LUIS","MARSILAC","MIRANDOPOLIS","MOEMA","PARELHEIROS","PEDREIRA","PLANALTO PAULISTA","SACOMA","SANTO AMARO","SAUDE","SOCORRO","VILA ANDRADE","VILA CLEMENTINO","VILA CRUZEIRO","VILA GUARANI","VILA MARIANA","VILA MASCOTE","VILA MORAES","VILA SANTA CATARINA","VILA SOFIA"],
  "Zona Oeste":["ALTO DA LAPA","ALTO DE PINHEIROS","AGUA BRANCA","BARRA FUNDA","BUTANTA","CITY AMERICA","JAGUARA","JAGUARE","JARDIM BONFIGLIOLI","JARDIM ESTER","JARDIM PAULISTA","JARDIM PAULISTANO","JARDIM MONTE KEMEL","LAPA","MORUMBI","PACAEMBU","PERDIZES","PINHEIROS","POMPEIA","RAPOSO TAVARES","RIO PEQUENO","SUMARE","SUMAREZINHO","VILA HAMBURGUESA","VILA IPOJUCA","VILA LEOPOLDINA","VILA MADALENA","VILA POMPEIA","VILA ROMANA","VILA SONIA","VILA SUZANA"],
  "Centro":["ACLIMACAO","BELA VISTA","BOM RETIRO","CAMBUCI","CAMPOS ELISEOS","CENTRO","CERQUEIRA CESAR","CONSOLACAO","HIGIENOPOLIS","LIBERDADE","PARI","REPUBLICA","SANTA CECILIA","SE","VILA BUARQUE"]
};

function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g," ").trim()}

export function saoPauloZone(municipio:string,bairro:string):SaoPauloZone{
  if(normalize(municipio)!=="SAO PAULO")return"Não classificada";
  const name=normalize(bairro);
  for(const[zone,names]of Object.entries(groups)as[Exclude<SaoPauloZone,"Não classificada">,string[]][])if(names.some(x=>name===x||name.includes(x)))return zone;
  return"Não classificada";
}
